---
/**:
  joy_node:
    ros__parameters:
      dev: /dev/input/js0
      deadzone: 0.1
      autorepeat_rate: 20.0

  joy2twist:
    ros__parameters:
      axis_linear:
        x: 1
        y: 0
      scale_linear:
        x: 0.7
        y: 0.7
      scale_linear_turbo:
        x: 1.5
        y: 1.5

      axis_angular:
        yaw: 3
      scale_angular:
        yaw: 1.0
      scale_angular_turbo:
        yaw: 1.5

      require_enable_button: true
      enable_button: 4  # LB
      enable_turbo_button: 5 # RB
      publish_stamped_twist: false
