---
/**/controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
    drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController

/**/imu_broadcaster:
  ros__parameters:
    tf_frame_prefix_enable: false
    sensor_name: <namespace>/imu
    frame_id: imu_link
    static_covariance_orientation: [1.9e-3, 0.0, 0.0, 0.0, 1.9e-3, 0.0, 0.0, 0.0, 1.9e-3] # Values taken from datasheet
    static_covariance_angular_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0e-3] # Values measured experimentally
    static_covariance_linear_acceleration: [6.4e-2, 0.0, 0.0, 0.0, 2.2e-2, 0.0, 0.0, 0.0, 0.0] # Values measured experimentally

/**/drive_controller:
  ros__parameters:
    tf_frame_prefix_enable: false

    front_left_wheel_name: fl_wheel_joint
    front_right_wheel_name: fr_wheel_joint
    rear_left_wheel_name: rl_wheel_joint
    rear_right_wheel_name: rr_wheel_joint

    wheel_separation_x: 0.170
    wheel_separation_y: 0.270
    wheel_radius: 0.047

    wheel_separation_x_multiplier: 0.95  # Based on real measurements
    wheel_separation_y_multiplier: 0.95  # Based on real measurements

    wheel_radius_multiplier: 1.05  # Based on real measurements

    # Feedback from motors is published at around 20 Hz
    publish_rate: 20.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [3.3e-5, 3.3e-5, 0.0, 0.0, 0.0, 2.8e-3] # Values measured experimentally

    # Whether to use feedback or commands for odometry calculations
    open_loop: false

    # Update odometry from velocity
    # in sensor fusion only velocity is used and with this setting it is more accurate
    position_feedback: false
    # velocity computation filtering
    velocity_rolling_window_size: 1

    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # Limits from manual https://husarion.com/manuals/rosbot-xl/#hardware-guide
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        # top speed is around 0.8m/s
        max_velocity: 1.0 # m/s
        # min_velocity -  When unspecified, -max_velocity is used
        max_acceleration: 0.75 # m/s^2
        # min_acceleration - When unspecified, -max_acceleration is used.
        max_jerk: 0.0 # m/s^3
      y:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        # top speed is around 0.8m/s
        max_velocity: 1.0 # m/s
        # min_velocity -  When unspecified, -max_velocity is used
        max_acceleration: 0.5 # m/s^2
        # min_acceleration - When unspecified, -max_acceleration is used.
        max_jerk: 0.0 # m/s^3

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 3.14 # rad/s
        # min_velocity -  When unspecified, -max_velocity is used
        max_acceleration: 3.0 # rad/s^2
        # min_acceleration - When unspecified, -max_acceleration is used.
        max_jerk: 0.0 # rad/s^3

# Based on: https://github.com/ROBOTIS-GIT/open_manipulator/blob/humble/open_manipulator_x_bringup/config/hardware_controller_manager.yaml
/**/manipulator_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4

    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 200.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

/**/gripper_controller:
  ros__parameters:
    joint: gripper_left_joint
    state_interfaces:
      - position
    command_interfaces:
      - position
    conversion_factor: 0.0001
